Fix bedrock tool input schema
The todo extension added in https://github.com/block/goose/pull/4868
causes errors with bedrock because bedrock expects an input schema.

Without this fix, bedrock tool calls fail with

Error: Server error: Failed to call Bedrock:
ValidationException(ValidationException { message: Some("The value at
toolConfig.tools.3.toolSpec.inputSchema.json.type must be one of the
following: object."), meta: ErrorMetadata { code:
Some("ValidationException"), message: Some("The value at
toolConfig.tools.3.toolSpec.inputSchema.json.type must be one of the
following: object."), extras: Some({"aws_request_id":
"9813e4c5-607f-47fc-8a6a-4387ef28acb7"}) } })

Signed-off-by: alexyao2015 <alexyao2015@users.noreply.github.com>